"""add_export_file_size

Revision ID: 0d29a4c58201
Revises: 874ad52ec5a2
Create Date: 2026-02-25 23:25:40.244803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d29a4c58201'
down_revision: Union[str, Sequence[str], None] = '874ad52ec5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_jobs', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_jobs', 'file_size_bytes')
    # ### end Alembic commands ###
