"""add_export_filter_columns

Revision ID: 83c80e7f103e
Revises: 0d29a4c58201
Create Date: 2026-03-04 15:46:49.478076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c80e7f103e'
down_revision: Union[str, Sequence[str], None] = '0d29a4c58201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_jobs', sa.Column('smoothing', sa.String(), nullable=True))
    op.add_column('export_jobs', sa.Column('stabilization', sa.Integer(), server_default='0', nullable=False))
    op.add_column('export_jobs', sa.Column('denoising', sa.Integer(), server_default='0', nullable=False))
    op.add_column('export_jobs', sa.Column('color_correction', sa.String(), nullable=True))
    op.add_column('export_jobs', sa.Column('brightness', sa.Float(), nullable=True))
    op.add_column('export_jobs', sa.Column('contrast', sa.Float(), nullable=True))
    op.add_column('export_jobs', sa.Column('saturation', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_jobs', 'saturation')
    op.drop_column('export_jobs', 'contrast')
    op.drop_column('export_jobs', 'brightness')
    op.drop_column('export_jobs', 'color_correction')
    op.drop_column('export_jobs', 'denoising')
    op.drop_column('export_jobs', 'stabilization')
    op.drop_column('export_jobs', 'smoothing')
    # ### end Alembic commands ###
